### ISSUE TITLE
Newly registered Python indexes are wrong

### ISSUE THREAD

**Issue by fridex** [thoth-station/pulp-pypi-sync-job#33]
**Describe the bug**

```
 {
  "url": "https://pulp.operate-first.cloud/https://pulp-api-5c5f4669d8-qgvvh/pypi/gym-donkeycar/simple"
 },
 {
  "url": "https://pulp.operate-first.cloud/https://pulp-api-5c5f4669d8-qgvvh/pypi/test/simple"
 },
 {
  "url": "https://pulp.operate-first.cloud/https://pulp-api-5c5f4669d8-qgvvh/pypi/hello-world/simple"
```

**To Reproduce**
1. Go to stage environment
2. Check registered Python indexes available on Pulp
3. See the error

**Expected behavior**

Index URLs registered should be valid.

**Comment by Gregory-Pereira** [comment]
Just to clarify by `staging environment`, you mean where the job is actually running on OCP4 in `thoth-frontend-prod` correct? At first I thought you were referring to a separate staging deployment of Pulp similar to https://pulp.operate-first.cloud.

**Comment by fridex** [comment]
> Just to clarify by `staging environment`, you mean where the job is actually running on OCP4 in `thoth-frontend-prod` correct? 

I mean OCP4 deployment where the ingestion is done. It should be thoth-frontend-stage in OCP4.

**Comment by fridex** [comment]
> > Just to clarify by `staging environment`, you mean where the job is actually running on OCP4 in `thoth-frontend-prod` correct?
> 
> I mean OCP4 deployment where the ingestion is done. It should be thoth-frontend-stage in OCP4.

I mean, the deployment is OCP4 stage where the ingestion runs. The job itself runs in thoth-frontend-stage. Hope it clarifies and and sorry for the confusion.

**Comment by Gregory-Pereira** [comment]
Currently testing changes introduced in [pull 36](https://github.com/thoth-station/pulp-pypi-sync-job/pull/36)  on [OCP4 thoth-frontend-stage](https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/thoth-frontend-stage/pods/pulp-pypi-sync-job-after-url-changes-zrr8z/). Ran without issues.

**Comment by fridex** [comment]
> Currently testing changes introduced in [pull 36](https://github.com/thoth-station/pulp-pypi-sync-job/pull/36) on [OCP4 thoth-frontend-stage](https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/thoth-frontend-stage/pods/pulp-pypi-sync-job-after-url-changes-zrr8z/). Ran without issues.

The container succeeded, but I cannot see any indexes actually registered. There should be [the donkeycar index present](https://pulp.operate-first.cloud/pypi/gym-donkeycar/simple/), but it is not listed in the `/python-package-index` listing.

**Comment by Gregory-Pereira** [comment]
Got It, I haven't seen this job run before so thanks for sharing, I will look into it. Can you tell me where you were expecting to see that `/python-package-index` so I can dig into it?

**Comment by fridex** [comment]
> Got It, I haven't seen this job run before so thanks for sharing, I will look into it. Can you tell me where you were expecting to see that `/python-package-index` so I can dig into it?

I think it is due to pulp-pypi-sync-job not being updated in the stage (it was still running old code). I've tried to bump the image version, let's see. Thanks for digging into this 👍🏻

**Comment by fridex** [comment]
I can confirm the job registers indexes correctly. Thanks again for your time. 💯

**Comment by Gregory-Pereira** [comment]
Perfect, thanks for all the help Frido!
